# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/filipe/Documentos/Matrias/Projetos-de-Circuitos-Reconfigur-veis_UnB_2019_1/ula_ponto_fixo/ula_ponto_fixo.srcs/sources_1/ip/div_gen_1/div_gen_1.xci
# IP: The module: 'div_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/filipe/Documentos/Matrias/Projetos-de-Circuitos-Reconfigur-veis_UnB_2019_1/ula_ponto_fixo/ula_ponto_fixo.srcs/sources_1/ip/div_gen_1/div_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/filipe/Documentos/Matrias/Projetos-de-Circuitos-Reconfigur-veis_UnB_2019_1/ula_ponto_fixo/ula_ponto_fixo.srcs/sources_1/ip/div_gen_1/div_gen_1.xci
# IP: The module: 'div_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/filipe/Documentos/Matrias/Projetos-de-Circuitos-Reconfigur-veis_UnB_2019_1/ula_ponto_fixo/ula_ponto_fixo.srcs/sources_1/ip/div_gen_1/div_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
